language: elixir
elixir:
  - 1.0.0
  - 1.0.1
  - 1.0.2
  - 1.0.3
  - 1.0.4
otp_release:
  - 17.0
  - 17.4
env:
  - ELIXIR_VERSION="1.0.0"
  - ELIXIR_VERSION="1.0.4"
before_install:
  - wget http://s3.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip
  - unzip -d elixir v$ELIXIR_VERSION.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report